/**
 * BlackJack Class
 * Author: Shady Ibrahim
 */

package main;

import java.io.File;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;

public class BlackJack extends javax.swing.JFrame {

    /*
     * Creates new form BlackJack
     */
                
    int count = 0, total = 0, dTotal = 0, check1 = 0, check2 = 0, check3 = 0, countAces = 0, howmany2 = 0, howmany3 = 0, dCount = 0, bet = checkBank() + 122, cha = checkBank();
    static ArrayList<String> cards = new ArrayList<>();
    
    public BlackJack()
    {        
        initComponents();
        startCards(); 
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblDealerHand = new javax.swing.JLabel();
        lblYourHand = new javax.swing.JLabel();
        lblPlayerimg1 = new javax.swing.JLabel();
        lblPlayerimg2 = new javax.swing.JLabel();
        lblPlayerimg3 = new javax.swing.JLabel();
        lblPlayerimg4 = new javax.swing.JLabel();
        lblPlayerimg5 = new javax.swing.JLabel();
        lblPlayerimg6 = new javax.swing.JLabel();
        btnHitMe = new javax.swing.JButton();
        btnStay = new javax.swing.JButton();
        lblMyTotal = new javax.swing.JLabel();
        lblDealerTotal = new javax.swing.JLabel();
        lblDealer2 = new javax.swing.JLabel();
        lblDealer1 = new javax.swing.JLabel();
        lblDealer3 = new javax.swing.JLabel();
        lblDealer4 = new javax.swing.JLabel();
        lblDealer5 = new javax.swing.JLabel();
        lblDealer6 = new javax.swing.JLabel();
        lblBank = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblTitle.setText("Let's Play BlackJack");

        lblDealerHand.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        lblDealerHand.setText("Dealer's Hand: ");

        lblYourHand.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        lblYourHand.setText("Your Hand: ");

        lblPlayerimg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/55.png"))); // NOI18N
        lblPlayerimg1.setToolTipText("");

        lblPlayerimg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/55.png"))); // NOI18N

        lblPlayerimg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/55.png"))); // NOI18N
        lblPlayerimg3.setToolTipText("");

        lblPlayerimg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/55.png"))); // NOI18N
        lblPlayerimg4.setToolTipText("");

        lblPlayerimg5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/55.png"))); // NOI18N
        lblPlayerimg5.setToolTipText("");

        lblPlayerimg6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/55.png"))); // NOI18N
        lblPlayerimg6.setToolTipText("");

        btnHitMe.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnHitMe.setText("Hit Me!");
        btnHitMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitMeActionPerformed(evt);
            }
        });

        btnStay.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnStay.setText("Stay");
        btnStay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStayActionPerformed(evt);
            }
        });

        lblMyTotal.setFont(new java.awt.Font("Ubuntu", 0, 72)); // NOI18N
        lblMyTotal.setText("21");

        lblDealerTotal.setFont(new java.awt.Font("Ubuntu", 0, 72)); // NOI18N
        lblDealerTotal.setText("—");

        lblDealer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/55.png"))); // NOI18N

        lblDealer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N

        lblDealer3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/55.png"))); // NOI18N

        lblDealer4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/55.png"))); // NOI18N

        lblDealer5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/55.png"))); // NOI18N

        lblDealer6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/55.png"))); // NOI18N

        lblBank.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        lblBank.setText("Bank: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitle)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDealer1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDealer3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblDealer4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDealer5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDealer6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDealer2)))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDealerHand)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(lblDealerTotal))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(btnStay, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(lblBank)
                                .addGap(124, 124, 124)
                                .addComponent(btnHitMe, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPlayerimg2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPlayerimg1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPlayerimg3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPlayerimg4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(lblPlayerimg6))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPlayerimg5)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblYourHand)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblMyTotal)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDealer1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDealerHand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDealerTotal))
                    .addComponent(lblDealer3)
                    .addComponent(lblDealer4)
                    .addComponent(lblDealer5)
                    .addComponent(lblDealer2)
                    .addComponent(lblDealer6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblPlayerimg6, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblPlayerimg2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblPlayerimg1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblPlayerimg3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblPlayerimg4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblPlayerimg5, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblYourHand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMyTotal)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnStay, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBank))
                    .addComponent(btnHitMe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitMeActionPerformed

        if(count == 0)
        {
            lblPlayerimg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/" + BlackJackSrc.playerAdd().get(BlackJackSrc.player1.size() - 1) + ".png")));
            System.out.println(BlackJack.cards);
        }
        else if(count == 1)
        {
            lblPlayerimg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/" + BlackJackSrc.playerAdd().get(BlackJackSrc.player1.size() - 1) + ".png")));
            System.out.println(BlackJack.cards);
        }
        else if(count == 2)
        {
            lblPlayerimg5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/" + BlackJackSrc.playerAdd().get(BlackJackSrc.player1.size() - 1) + ".png")));
            System.out.println(BlackJack.cards);
        }
        else if(count == 3)
        {
            lblPlayerimg6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/" + BlackJackSrc.playerAdd().get(BlackJackSrc.player1.size() - 1) + ".png")));
            System.out.println(BlackJack.cards);
        }
        
        count++;
        
        total = calcTotal(BlackJackSrc.player1);
        lblMyTotal.setText("" + total);
        
        if(total > 21)
        {
            JOptionPane.showMessageDialog(null,"Your total is over 21! You Lost $" + bet + "!", "You Lose!", JOptionPane.ERROR_MESSAGE);
            loseMoney();
            startCards(); 
        }
        
    }//GEN-LAST:event_btnHitMeActionPerformed

    private void btnStayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStayActionPerformed
        
        dTotal = calcTotal(BlackJackSrc.player2);
        
        lblDealer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/" + BlackJackSrc.player2.get(0) + ".png")));
        lblDealer3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/" + BlackJackSrc.player2.get(1) + ".png")));
        
        if(dTotal > total)
        {
            lblDealerTotal.setText("" + dTotal);
            JOptionPane.showMessageDialog(null,"Dealer wins! You lost $" + bet + "!", "You Lose!", JOptionPane.ERROR_MESSAGE);
            loseMoney();            
            startCards();
        }
        else if(dTotal == total)
        {
            lblDealerTotal.setText("" + dTotal); 
            JOptionPane.showMessageDialog(null,"It's a tie. No money awarded.", "Tie", JOptionPane.INFORMATION_MESSAGE);   
            startCards();
        }
        else
        {
            while(dTotal < total)
            {
                if(dCount == 0)
                {
                    lblDealer4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/" + BlackJackSrc.dealerAdd().get(BlackJackSrc.player2.size() - 1) + ".png")));                    
                }
                else if(dCount == 1)
                {
                    lblDealer5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/" + BlackJackSrc.dealerAdd().get(BlackJackSrc.player2.size() - 1) + ".png")));
                }
                else if(dCount == 2)
                {
                    lblDealer6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/" + BlackJackSrc.dealerAdd().get(BlackJackSrc.player2.size() - 1) + ".png")));
                }
                if(dCount == 3)
                {
                    lblDealer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/" + BlackJackSrc.dealerAdd().get(BlackJackSrc.player2.size() - 1) + ".png")));
                }
                
                dCount++;
                
                dTotal = calcTotal(BlackJackSrc.player2);
                
                if(dTotal > total && dTotal <= 21)
                {
                    lblDealerTotal.setText("" + dTotal);
                    JOptionPane.showMessageDialog(null,"Dealer wins, You lost $" + bet + "!", "You Lose!", JOptionPane.ERROR_MESSAGE);
                    loseMoney();
                    startCards();                    
                    break;
                }
                else if(dTotal > 21)
                {
                    lblDealerTotal.setText("" + dTotal); 
                    JOptionPane.showMessageDialog(null,"You won, You gained $" + bet + "!", "You Won!", JOptionPane.WARNING_MESSAGE);     
                    gainMoney();
                    startCards();
                    break;
                }
                else if(dTotal == total)
                {
                    lblDealerTotal.setText("" + dTotal); 
                    JOptionPane.showMessageDialog(null,"It's a tie. No money awarded.", "Tie", JOptionPane.INFORMATION_MESSAGE);
                    startCards();
                    break;
                }
            }  
        }      
    }//GEN-LAST:event_btnStayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlackJack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitMe;
    private javax.swing.JButton btnStay;
    private javax.swing.JLabel lblBank;
    private javax.swing.JLabel lblDealer1;
    private javax.swing.JLabel lblDealer2;
    private javax.swing.JLabel lblDealer3;
    private javax.swing.JLabel lblDealer4;
    private javax.swing.JLabel lblDealer5;
    private javax.swing.JLabel lblDealer6;
    private javax.swing.JLabel lblDealerHand;
    private javax.swing.JLabel lblDealerTotal;
    private javax.swing.JLabel lblMyTotal;
    private javax.swing.JLabel lblPlayerimg1;
    private javax.swing.JLabel lblPlayerimg2;
    private javax.swing.JLabel lblPlayerimg3;
    private javax.swing.JLabel lblPlayerimg4;
    private javax.swing.JLabel lblPlayerimg5;
    private javax.swing.JLabel lblPlayerimg6;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblYourHand;
    // End of variables declaration//GEN-END:variables
    
    public int calcTotal(ArrayList<String> x)
    {
        int calcd = 0;
        
        for(int i = 0; i < x.size(); i++)
        {            
            if(Integer.parseInt(x.get(i).substring(1)) > 10 && Integer.parseInt(x.get(i).substring(1)) < 14)
            {                
                calcd += 10;
            }
            else if(Integer.parseInt((x.get(i).substring(1))) == 14)
            {
                calcd += 11;                
            }
            else
            {                
                calcd += Integer.parseInt(x.get(i).substring(1));
            }
        }
        
        if(calcd > 21)
        {
            countAces = 0;
            for(int i = 0; i < x.size(); i++)
            {
                switch (x.get(i)) {
                    case "114":
                        countAces++;
                        break;
                    case "214":
                        countAces++;
                        break;
                    case "314":
                        countAces++;
                        break;
                    case "414":
                        countAces++;
                        break;
                }
            }
            
            if(countAces == 1)
            {
                calcd = 0;
                check1++;
                for(int i = 0; i < x.size(); i++)
                {            
                    if(Integer.parseInt(x.get(i).substring(1)) > 10 && Integer.parseInt(x.get(i).substring(1)) < 14)
                    {                
                        calcd += 10;
                    }
                    else if(Integer.parseInt(x.get(i).substring(1)) == 14)
                    {
                        calcd+= 1;                                                                             
                    }
                    else
                    {                
                        calcd += Integer.parseInt(x.get(i).substring(1));;
                    }
                }                
            }
            else if(countAces == 2)
            {
                calcd = 0;
                check2++;
                for(int i = 0; i < x.size(); i++)
                {            
                    if(Integer.parseInt(x.get(i).substring(1)) > 10 && Integer.parseInt(x.get(i).substring(1)) < 14)
                    {                
                        calcd += 10;
                    }
                    else if(Integer.parseInt(x.get(i).substring(1)) == 14)
                    {
                        if(check2 == 1)
                        {
                            calcd += 11;
                            check2 = 0;
                        }
                        else
                        {
                            calcd += 1;
                        }
                    }
                    else
                    {                
                        calcd += Integer.parseInt(x.get(i).substring(1));
                    }
                }
            }
            else if(countAces == 3)
            {
                calcd = 0;
                check3++;
                for(int i = 0; i < x.size(); i++)
                {             
                    if(Integer.parseInt(x.get(i).substring(1)) > 10 && Integer.parseInt(x.get(i).substring(1)) < 14)
                    {                
                        calcd += 10;
                    }
                    else if(Integer.parseInt(x.get(i).substring(1)) == 14)
                    {
                        if(check3 == 1)
                        {
                            calcd+= 11;                           
                        }
                        else
                        {
                            calcd += 1;                            
                        }
                    }
                    else
                    {                
                        calcd += Integer.parseInt(x.get(i).substring(1));
                    }
                }
            }
        }
        
        return calcd;
    }
    
    public void startCards()
    {
        total = 0;
        dTotal = 0;
        dCount = 0;
        count = 0;
        cha = checkBank();
        bet = 0;
        System.out.println(cha);
            
        lblPlayerimg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/55.png")));
        lblPlayerimg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/55.png")));
        lblPlayerimg5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/55.png")));
        lblPlayerimg6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/55.png")));
        lblDealer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png")));
        lblDealer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/55.png")));
        lblDealer4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/55.png")));
        lblDealer5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/55.png")));
        lblDealer6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/55.png")));
               
        cards = PreGame.createShuffle();
        
        new BlackJackSrc();        
        
        lblPlayerimg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/" + BlackJackSrc.player1.get(0) + ".png")));        

        lblPlayerimg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/" + BlackJackSrc.player1.get(1) + ".png")));
        
        lblDealer3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/" + BlackJackSrc.player2.get(0) + ".png")));
        
        total = calcTotal(BlackJackSrc.player1);       
        
        lblMyTotal.setText("" + total);
        lblDealerTotal.setText("—");
        lblBank.setText("Bank: $" + checkBank());
        
        
        new java.util.Timer().schedule( 
        new java.util.TimerTask()
        {
            @Override
            public void run()
            {
                if(calcTotal(BlackJackSrc.player1) == 21 && calcTotal(BlackJackSrc.player2) != 21)
                {
                    JOptionPane.showMessageDialog(null,"You instantly won with BlackJack! You won $250!", "BlackJack!", JOptionPane.WARNING_MESSAGE);
                    blackJack();
                    startCards();
                }
                else if(calcTotal(BlackJackSrc.player2) == 21 && calcTotal(BlackJackSrc.player1) != 21)
                {                    
                    JOptionPane.showMessageDialog(null,"Dealer has blackjack! You instantly lost $125!", "Oh no!", JOptionPane.ERROR_MESSAGE);
                    dealerJack();
                    startCards();                    
                }
                else
                {
                    
                    bet = Integer.parseInt(JOptionPane.showInputDialog(null,"Input your bet:", "Let's Bet", JOptionPane.QUESTION_MESSAGE));
                    
                    while(true)
                    {                        
                        if(bet > checkBank())
                        {                                                        
                            bet = Integer.parseInt(JOptionPane.showInputDialog(null, "Bet too high! Input your bet again:", "Let's Bet", JOptionPane.QUESTION_MESSAGE));
                        }
                        else
                        {
                            break;
                        }                        
                    }    
                }
            }
        }, 1);       
    }
    
    public int checkBank()
    {
        File bank = new File (LoginForm.getUser().toLowerCase() + ".txt");
        
        if(bank.exists())
        {
            System.out.println("exists");
            try
            {
                Scanner ching = new Scanner(bank);
                
                cha = ching.nextInt();
                
                if(cha == 0)
                {
                    cha = 10;
                }                
            }
            catch (Exception e)
            {
                System.out.println("Error Occured: " + e.getMessage());
            }
        }
        else
        {
            System.out.print("well im here");
            try
            {
                bank.createNewFile();                
                PrintStream printer = new PrintStream(bank);
                printer.print("100");
                
                Scanner ching = new Scanner(bank);

                cha = ching.nextInt();                                                
            }
            catch (Exception e)
            {
                System.out.println(e.getMessage());
                System.out.println(e.getStackTrace());
            }            
        }                
        
        return cha;
    }
    
    public void gainMoney()
    {
        File bank = new File (LoginForm.getUser().toLowerCase() + ".txt");
                
        try
        {
            PrintStream printer = new PrintStream(bank);
            printer.print(cha + bet);           
        }
        catch (Exception e)
        {
            System.out.println("Error occured: " + e.getMessage());
        }
    }
    
    public void loseMoney()
    {
        File bank = new File (LoginForm.getUser().toLowerCase() + ".txt");
                
        try
        {
            PrintStream printer = new PrintStream(bank);
            if(cha - bet <= 0)
            {
                printer.print("0");
            }
            else
            {
                printer.print(cha - bet); 
            }                      
        }
        catch (Exception e)
        {
            System.out.println("Error occured: " + e.getMessage());
        }
    }
    
    public void blackJack()
    {
        File bank = new File (LoginForm.getUser().toLowerCase() + ".txt");
                
        try
        {
            PrintStream printer = new PrintStream(bank);
            printer.print(250 + cha);           
        }
        catch (Exception e)
        {
            System.out.println("Error occured: " + e.getMessage());
        }
    }
    
    public void dealerJack()
    {
        File bank = new File (LoginForm.getUser().toLowerCase() + ".txt");
                
        try
        {
            if(cha - 125 < 0)
            {
                PrintStream printer = new PrintStream(bank);
                printer.print("10");
            }
            else
            {
                PrintStream printer = new PrintStream(bank);
                printer.print(cha - 125);                 
            }          
        }
        catch (Exception e)
        {
            System.out.println("Error occured: " + e.getMessage());
        }
    }
}