/**
 * Change Account Details Class
 * Author: Shady Ibrahim
 */

package main;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.Scanner;

public class ChangeAccount extends javax.swing.JFrame {

    /**
     * Creates new form ChangeAccount
     */
    public ChangeAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblOldPass = new javax.swing.JLabel();
        txtNewPass = new javax.swing.JPasswordField();
        btnSubmit = new javax.swing.JButton();
        lblPassword = new javax.swing.JLabel();
        lblChangePass = new javax.swing.JLabel();
        txtConfirmNewPass = new javax.swing.JPasswordField();
        lblPassword1 = new javax.swing.JLabel();
        lblTaken = new javax.swing.JLabel();
        txtOldPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        lblTitle.setText("Account Settings");
        lblTitle.setToolTipText("");

        lblOldPass.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblOldPass.setText("Old Password:");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblPassword.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblPassword.setText("New Password:");

        lblChangePass.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        lblChangePass.setText("Change Password:");
        lblChangePass.setToolTipText("");

        lblPassword1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblPassword1.setText("Confirm Password:");

        lblTaken.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(lblChangePass)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPassword)
                                .addComponent(lblOldPass)
                                .addComponent(lblPassword1))
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNewPass, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                .addComponent(txtConfirmNewPass, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                .addComponent(txtOldPass)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblTaken)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSubmit)
                            .addGap(52, 52, 52))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOldPass)
                    .addComponent(txtOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword1)
                    .addComponent(txtConfirmNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnSubmit)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTaken)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        String oldPass = txtOldPass.getText(), newPass = txtNewPass.getText(); String currentPass = "";
        File usernames = new File ("usernames.txt"); File passwords = new File ("passwords.txt");
        
        ArrayList<String> user = new ArrayList<>();
        ArrayList<String> pass = new ArrayList<>();
        
        try
        {
            Scanner userCheck = new Scanner (usernames); Scanner passCheck = new Scanner (passwords);
            while(userCheck.hasNext())
            {
                String thisUser = userCheck.next(); String thisPass = passCheck.next();
                user.add(thisUser);
                pass.add(thisPass);                
            }         
        }
        catch(Exception e)
        {
            System.out.println("Error occured.");
            System.out.println(e.getMessage());
        }
        
        for(int i = 0; i < LoginForm.getPasses().size(); i++)
        {
            if(user.get(i).equals(LoginForm.getUser()))
            {
                currentPass = pass.get(i);
                break;
            }
        }
        
        System.out.println("current pass: " + currentPass);
        System.out.println("oldPass: " + methods.encrypt(oldPass)); 
        System.out.println(user);
        System.out.println(pass);
        
        if(methods.encrypt(oldPass).equals(currentPass))
        {
            try
            {
                if(txtNewPass.getText().equals(txtConfirmNewPass.getText()))
                {
                    PrintStream killit = new PrintStream (passwords);
                    killit.print("");
                    for(int i = 0; i < LoginForm.getPasses().size(); i++)
                    {                        
                        if(LoginForm.getUsers().get(i).equals(LoginForm.getUser()))
                        {
                            FileWriter passfw = new FileWriter(passwords, true); BufferedWriter passbw = new BufferedWriter(passfw);
                            passbw.write(methods.encrypt(newPass) +"\n"); passbw.close();                            
                        }
                        else
                        {
                            FileWriter passfw = new FileWriter(passwords, true); BufferedWriter passbw = new BufferedWriter(passfw);
                            passbw.write(LoginForm.getPasses().get(i) +"\n"); passbw.close();
                            lblTaken.setForeground(Color.blue); lblTaken.setText("Password change successful.");
                        }
                    }
                }
                else
                {
                    lblTaken.setForeground(Color.red); lblTaken.setText("New passwords don't match.");               
                }
            }
            catch(Exception e)
            {
                System.out.println("Error occured.");
                System.out.println(e.getMessage());
            }
        }
        else
        {
            lblTaken.setForeground(Color.red); lblTaken.setText("Old password incorrect.");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblChangePass;
    private javax.swing.JLabel lblOldPass;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblTaken;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPasswordField txtConfirmNewPass;
    private javax.swing.JPasswordField txtNewPass;
    private javax.swing.JPasswordField txtOldPass;
    // End of variables declaration//GEN-END:variables
}
