/**
 * Tic Tac Toe Simple Game
 * Author: Shady Ibrahim
 */

package main;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author shady
 */
public class TicTacToe extends javax.swing.JFrame {

    /**
     * Creates new form TicTacToe
    */
    
     int turns = 0, b1 = 0, b2 = 0, b3 = 0, b4 = 0, b5 = 0, b6 = 0, b7 = 0, b8 = 0, b9 = 0;
     int whoFirst = 1 + (int)(Math.random() * 2);
     String player1;
     String player2;
     
    public TicTacToe()
    {       
        initComponents();
        this.getContentPane().setBackground(new Color(172, 15, 42));
        restart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn12 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn31 = new javax.swing.JButton();
        btn32 = new javax.swing.JButton();
        btn33 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn23 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btn12.setBackground(java.awt.Color.black);
        btn12.setFont(new java.awt.Font("Ubuntu", 0, 100)); // NOI18N
        btn12.setContentAreaFilled(false);
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });

        btn11.setBackground(java.awt.Color.black);
        btn11.setFont(new java.awt.Font("Ubuntu", 0, 100)); // NOI18N
        btn11.setContentAreaFilled(false);
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });

        btn13.setBackground(java.awt.Color.black);
        btn13.setFont(new java.awt.Font("Ubuntu", 0, 100)); // NOI18N
        btn13.setContentAreaFilled(false);
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });

        btn31.setBackground(java.awt.Color.black);
        btn31.setFont(new java.awt.Font("Ubuntu", 0, 100)); // NOI18N
        btn31.setContentAreaFilled(false);
        btn31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn31ActionPerformed(evt);
            }
        });

        btn32.setBackground(java.awt.Color.black);
        btn32.setFont(new java.awt.Font("Ubuntu", 0, 100)); // NOI18N
        btn32.setContentAreaFilled(false);
        btn32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn32ActionPerformed(evt);
            }
        });

        btn33.setBackground(java.awt.Color.black);
        btn33.setFont(new java.awt.Font("Ubuntu", 0, 100)); // NOI18N
        btn33.setContentAreaFilled(false);
        btn33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn33ActionPerformed(evt);
            }
        });

        btn22.setBackground(java.awt.Color.black);
        btn22.setFont(new java.awt.Font("Ubuntu", 0, 100)); // NOI18N
        btn22.setContentAreaFilled(false);
        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });

        btn21.setBackground(java.awt.Color.black);
        btn21.setFont(new java.awt.Font("Ubuntu", 0, 100)); // NOI18N
        btn21.setContentAreaFilled(false);
        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });

        btn23.setBackground(java.awt.Color.black);
        btn23.setFont(new java.awt.Font("Ubuntu", 0, 100)); // NOI18N
        btn23.setContentAreaFilled(false);
        btn23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn23ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/whitelineh.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/whitelineh.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/whitelinev.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/whitelinev.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/whitelinev.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/whitelinev.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/whitelinev.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/whitelinev.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 50)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Tic Tac Toe!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn31, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn32, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn33, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn23, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn23, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn31, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn32, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn33, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(24, Short.MAX_VALUE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        if(b2 == 0)
        {
            turns++;
            if(whoFirst == 1 && turns == 1)
        {
            btn12.setText("X");
            btn12.setForeground(Color.magenta);
        }
        else if(whoFirst == 2 && turns == 1)
        {
            btn12.setText("O");
            btn12.setForeground(Color.orange);
        }
        else if(whoFirst == 1 && turns % 2 == 1)
        {
            btn12.setText("X");
            btn12.setForeground(Color.magenta);
        }
        else if(whoFirst == 2 && turns % 2 == 1)
        {
            btn12.setText("O");
            btn12.setForeground(Color.orange);
        }
        else if(whoFirst == 2 && turns % 2 == 0)
        {
            btn12.setText("X");
            btn12.setForeground(Color.magenta);
        }
        else
        {
            btn12.setText("O");
            btn12.setForeground(Color.orange);
        }
        b2++;
        checkWin();
        }        
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        if(b1 == 0)
        {
            turns++;
            if(whoFirst == 1 && turns == 1)
        {
            btn11.setText("X");
            btn11.setForeground(Color.magenta);
        }
        else if(whoFirst == 2 && turns == 1)
        {
            btn11.setText("O");
            btn11.setForeground(Color.orange);
        }
        else if(whoFirst == 1 && turns % 2 == 1)
        {
            btn11.setText("X");
            btn11.setForeground(Color.magenta);
        }
        else if(whoFirst == 2 && turns % 2 == 1)
        {
            btn11.setText("O");
            btn11.setForeground(Color.orange);
        }
        else if(whoFirst == 2 && turns % 2 == 0)
        {
            btn11.setText("X");
            btn11.setForeground(Color.magenta);
        }
        else
        {
            btn11.setText("O");
            btn11.setForeground(Color.orange);
        }
        b1++;
        checkWin();
        }
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        if(b3 == 0)
        {
            turns++;
            if(whoFirst == 1 && turns == 1)
        {
            btn13.setText("X");
            btn13.setForeground(Color.magenta);
        }
        else if(whoFirst == 2 && turns == 1)
        {
            btn13.setText("O");
            btn13.setForeground(Color.orange);
        }
        else if(whoFirst == 1 && turns % 2 == 1)
        {
            btn13.setText("X");
            btn13.setForeground(Color.magenta);
        }
        else if(whoFirst == 2 && turns % 2 == 1)
        {
            btn13.setText("O");
            btn13.setForeground(Color.orange);
        }
        else if(whoFirst == 2 && turns % 2 == 0)
        {
            btn13.setText("X");
            btn13.setForeground(Color.magenta);
        }
        else
        {
            btn13.setText("O");
            btn13.setForeground(Color.orange);
        }
        b3++;
        checkWin();
        }
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
        if(b4 == 0)
        {
            turns++;
            if(whoFirst == 1 && turns == 1)
        {
            btn21.setText("X");
            btn21.setForeground(Color.magenta);
        }
        else if(whoFirst == 2 && turns == 1)
        {
            btn21.setText("O");
            btn21.setForeground(Color.orange);
        }
        else if(whoFirst == 1 && turns % 2 == 1)
        {
            btn21.setText("X");
            btn21.setForeground(Color.magenta);
        }
        else if(whoFirst == 2 && turns % 2 == 1)
        {
            btn21.setText("O");
            btn21.setForeground(Color.orange);
        }
        else if(whoFirst == 2 && turns % 2 == 0)
        {
            btn21.setText("X");
            btn21.setForeground(Color.magenta);
        }
        else
        {
            btn21.setText("O");
            btn21.setForeground(Color.orange);
        }
        b4++;
        checkWin();
        }     
    }//GEN-LAST:event_btn21ActionPerformed

    private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
        if(b5 == 0)
        {
            turns++;
            if(whoFirst == 1 && turns == 1)
        {
            btn22.setText("X");
            btn22.setForeground(Color.magenta);
        }
        else if(whoFirst == 2 && turns == 1)
        {
            btn22.setText("O");
            btn22.setForeground(Color.orange);
        }
        else if(whoFirst == 1 && turns % 2 == 1)
        {
            btn22.setText("X");
            btn22.setForeground(Color.magenta);
        }
        else if(whoFirst == 2 && turns % 2 == 1)
        {
            btn22.setText("O");
            btn22.setForeground(Color.orange);
        }
        else if(whoFirst == 2 && turns % 2 == 0)
        {
            btn22.setText("X");
            btn22.setForeground(Color.magenta);
        }
        else
        {
            btn22.setText("O");
            btn22.setForeground(Color.orange);
        }
        b5++;
        checkWin();
        }      
    }//GEN-LAST:event_btn22ActionPerformed

    private void btn23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn23ActionPerformed
        if(b6 == 0){
            
            turns++;
            if(whoFirst == 1 && turns == 1)
        {
            btn23.setText("X");
            btn23.setForeground(Color.magenta);
        }
        else if(whoFirst == 2 && turns == 1)
        {
            btn23.setText("O");
            btn23.setForeground(Color.orange);
        }
        else if(whoFirst == 1 && turns % 2 == 1)
        {
            btn23.setText("X");
            btn23.setForeground(Color.magenta);
        }
        else if(whoFirst == 2 && turns % 2 == 1)
        {
            btn23.setText("O");
            btn23.setForeground(Color.orange);
        }
        else if(whoFirst == 2 && turns % 2 == 0)
        {
            btn23.setText("X");
            btn23.setForeground(Color.magenta);
        }
        else
        {
            btn23.setText("O");
            btn23.setForeground(Color.orange);
        }
        b6++;
        checkWin();
        }        
    }//GEN-LAST:event_btn23ActionPerformed

    private void btn31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn31ActionPerformed
        if(b7 == 0)
        {
            turns++;
            if(whoFirst == 1 && turns == 1)
        {
            btn31.setText("X");
            btn31.setForeground(Color.magenta);
        }
        else if(whoFirst == 2 && turns == 1)
        {
            btn31.setText("O");
            btn31.setForeground(Color.orange);
        }
        else if(whoFirst == 1 && turns % 2 == 1)
        {
            btn31.setText("X");
            btn31.setForeground(Color.magenta);
        }
        else if(whoFirst == 2 && turns % 2 == 1)
        {
            btn31.setText("O");
            btn31.setForeground(Color.orange);
        }
        else if(whoFirst == 2 && turns % 2 == 0)
        {
            btn31.setText("X");
            btn31.setForeground(Color.magenta);
        }
        else
        {
            btn31.setText("O");
            btn31.setForeground(Color.orange);
        }
        b7++;
        checkWin();
        }   
    }//GEN-LAST:event_btn31ActionPerformed

    private void btn32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn32ActionPerformed
        if(b8 == 0)
        {
            turns++;
            if(whoFirst == 1 && turns == 1)
        {
            btn32.setText("X");
            btn32.setForeground(Color.magenta);
        }
        else if(whoFirst == 2 && turns == 1)
        {
            btn32.setText("O");
            btn32.setForeground(Color.orange);
        }
        else if(whoFirst == 1 && turns % 2 == 1)
        {
            btn32.setText("X");
            btn32.setForeground(Color.magenta);
        }
        else if(whoFirst == 2 && turns % 2 == 1)
        {
            btn32.setText("O");
            btn32.setForeground(Color.orange);
        }
        else if(whoFirst == 2 && turns % 2 == 0)
        {
            btn32.setText("X");
            btn32.setForeground(Color.magenta);
        }
        else
        {
            btn32.setText("O");
            btn32.setForeground(Color.orange);
        }
        b8++;
        checkWin();
        }        
    }//GEN-LAST:event_btn32ActionPerformed

    private void btn33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn33ActionPerformed
        if(b9 == 0)
        {
            turns++;
            if(whoFirst == 1 && turns == 1)
        {
            btn33.setText("X");
            btn33.setForeground(Color.magenta);
        }
        else if(whoFirst == 2 && turns == 1)
        {
            btn33.setText("O");
            btn33.setForeground(Color.orange);
        }
        else if(whoFirst == 1 && turns % 2 == 1)
        {
            btn33.setText("X");
            btn33.setForeground(Color.magenta);
        }
        else if(whoFirst == 2 && turns % 2 == 1)
        {
            btn33.setText("O");
            btn33.setForeground(Color.orange);
        }
        else if(whoFirst == 2 && turns % 2 == 0)
        {
            btn33.setText("X");
            btn33.setForeground(Color.magenta);
        }
        else
        {
            btn33.setText("O");
            btn33.setForeground(Color.orange);
        }
        b9++;
        checkWin();
        }      
    }//GEN-LAST:event_btn33ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn23;
    private javax.swing.JButton btn31;
    private javax.swing.JButton btn32;
    private javax.swing.JButton btn33;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    public void checkWin()
    {
        //Horizontal wins
        
        if (btn11.getText().equals(btn12.getText()) && btn12.getText().equals(btn13.getText()) && btn11.getText().equals("") == false) {
                        
            if(btn11.getText().equals("X"))
            {
                JOptionPane.showMessageDialog(null, player1 + " wins!", "We have a winner!", JOptionPane.INFORMATION_MESSAGE);               
            }
            else
            {
                JOptionPane.showMessageDialog(null, player2 + " wins!", "We have a winner!", JOptionPane.INFORMATION_MESSAGE);
            }
            
            String playAgain = JOptionPane.showInputDialog(null, "Enter yes or no below:", "Play again?", JOptionPane.INFORMATION_MESSAGE);
            
            if(playAgain.contains("y") || playAgain.contains("Y"))
            {
                restart();
            }
            else
            {
                this.dispose();
            }
        }
        else if (btn21.getText().equals(btn22.getText()) && btn22.getText().equals(btn23.getText()) && btn21.getText().equals("") == false)
        {
            if(btn21.getText().equals("X"))
            {
                JOptionPane.showMessageDialog(null, player1 + " wins!", "We have a winner!", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null, player2 + " wins!", "We have a winner!", JOptionPane.INFORMATION_MESSAGE);
            }
                                    
            String playAgain = JOptionPane.showInputDialog(null, "Enter yes or no below:", "Play again?", JOptionPane.INFORMATION_MESSAGE);
            
            if(playAgain.contains("y") || playAgain.contains("Y"))
            {
                restart();
            }
            else
            {
                this.dispose();
            }            
        }
        else if (btn31.getText().equals(btn32.getText()) && btn32.getText().equals(btn33.getText()) && btn31.getText().equals(false))
        {
            if(btn31.getText().equals("X"))
            {
                JOptionPane.showMessageDialog(null, player1 + " wins!", "We have a winner!", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null, player2 + " wins!", "We have a winner!", JOptionPane.INFORMATION_MESSAGE);
            }            
                        
            String playAgain = JOptionPane.showInputDialog(null, "Enter yes or no below:", "Play again?", JOptionPane.INFORMATION_MESSAGE);
            
            if(playAgain.contains("y") || playAgain.contains("Y"))
            {
                restart();
            }
            else
            {
                this.dispose();
            }            
        }        
        //verticle wins
        else if (btn11.getText().equals(btn21.getText()) && btn21.getText().equals(btn31.getText()) && btn11.getText().equals("") == false) {
            
            if(btn11.getText().equals("X"))
            {
                JOptionPane.showMessageDialog(null, player1 + " wins!", "We have a winner!", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null, player2 + " wins!", "We have a winner!", JOptionPane.INFORMATION_MESSAGE);
            }
                        
            String playAgain = JOptionPane.showInputDialog(null, "Enter yes or no below:", "Play again?", JOptionPane.INFORMATION_MESSAGE);
            
            if(playAgain.contains("y") || playAgain.contains("Y"))
            {
                restart();
            }
            else
            {
                this.dispose();
            }
        } else if (btn12.getText().equals(btn22.getText()) && btn22.getText().equals(btn32.getText()) && btn12.getText().equals("") == false) {
            
            if(btn21.getText().equals("X"))
            {
                JOptionPane.showMessageDialog(null, player1 + " wins!", "We have a winner!", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null, player2 + " wins!", "We have a winner!", JOptionPane.INFORMATION_MESSAGE);
            }
            
            String playAgain = JOptionPane.showInputDialog(null, "Enter yes or no below:", "Play again?", JOptionPane.INFORMATION_MESSAGE);
            
            if(playAgain.contains("y") || playAgain.contains("Y"))
            {
                restart();
            }
            else
            {
                this.dispose();
            }            
        }
        else if (btn13.getText().equals(btn23.getText()) && btn23.getText().equals(btn33.getText()) && btn13.getText().equals("") == false) {
            
            if(btn13.getText().equals("X"))
            {
                JOptionPane.showMessageDialog(null, player1 + " wins!", "We have a winner!", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null, player2 + " wins!", "We have a winner!", JOptionPane.INFORMATION_MESSAGE);
            } 
            
            String playAgain = JOptionPane.showInputDialog(null, "Enter yes or no below:", "Play again?", JOptionPane.INFORMATION_MESSAGE);
            
            if(playAgain.contains("y") || playAgain.contains("Y"))
            {
                restart();
            }
            else
            {
                this.dispose();
            }            
        } //diagonal wins
        else if (btn11.getText().equals(btn22.getText()) && btn22.getText().equals(btn33.getText()) && btn11.getText().equals("") == false) {
            
            if(btn11.getText().equals("X"))
            {
                JOptionPane.showMessageDialog(null, player1 + " wins!", "We have a winner!", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null, player2 + " wins!", "We have a winner!", JOptionPane.INFORMATION_MESSAGE);
            }
            
            String playAgain = JOptionPane.showInputDialog(null, "Enter yes or no below:", "Play again?", JOptionPane.INFORMATION_MESSAGE);
            
            if(playAgain.contains("y") || playAgain.contains("Y"))
            {
                restart();
            }
            else
            {
                this.dispose();
            }            
        } else if (btn31.getText().equals(btn22.getText()) && btn22.getText().equals(btn13.getText()) && btn13.getText().equals("") == false) {

            if(btn31.getText().equals("X"))
            {
                JOptionPane.showMessageDialog(null, player1 + " wins!", "We have a winner!", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null, player2 + " wins!", "We have a winner!", JOptionPane.INFORMATION_MESSAGE);
            }
            
            String playAgain = JOptionPane.showInputDialog(null, "Enter yes or no below:", "Play again?", JOptionPane.INFORMATION_MESSAGE);
            
            if(playAgain.contains("y") || playAgain.contains("Y"))
            {
                restart();
            }
            else
            {
                this.dispose();
            }            
        }
        else if(turns == 9)
        {
            JOptionPane.showMessageDialog(null, "It's a draw!", "Cat's game!", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void restart()
    {
        turns = 0;
        whoFirst = 1 + (int)(Math.random() * 2);
        b1 = 0; b2 = 0; b3 = 0; b4 = 0; b5 = 0; b6 = 0; b7 = 0; b8 = 0; b9 = 0;
        
        btn11.setText("");
        btn12.setText("");
        btn13.setText("");
        btn21.setText("");
        btn22.setText("");
        btn23.setText("");
        btn31.setText("");
        btn32.setText("");
        btn33.setText("");        
                
        new java.util.Timer().schedule( 
        new java.util.TimerTask()
        {
            @Override
            public void run()
            {
                player1 = JOptionPane.showInputDialog(null,"Enter Player X's name:", "Player X", JOptionPane.INFORMATION_MESSAGE);
                player2 = JOptionPane.showInputDialog(null,"Enter Player O's name:", "Player O", JOptionPane.INFORMATION_MESSAGE);                
                if(whoFirst == 1)
                {
                    JOptionPane.showMessageDialog(null, player1 + " goes first!", "First Turn", JOptionPane.WARNING_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, player2 + " goes first!", "First Turn", JOptionPane.WARNING_MESSAGE);
                }             
            }
        }, 1); 
        
    }   
}
